[env:esp32doit-devkit-v1]
platform = espressif32@^6.9.0
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps =
	ESP32Async/ESPAsyncWebServer
	ESP32Async/AsyncTCP
	yiannisbourkelis/Uptime Library@^1.0.0
	adafruit/Adafruit SSD1306@^2.5.16
	adafruit/Adafruit GFX Library@^1.12.5
	adafruit/Adafruit BME280 Library@^2.3.0
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/Adafruit CCS811 Library@^1.1.3
